de_prob: [0.3, 0.7]
batch_facscale: 0.4
n_cells: 2000
n_reps: 5
n_batches: 4
frac_shared: [.5, 1.]
methods: ["scDEF", "scDEF_un", "Unintegrated", "NMF", "scHPF", "scVI", "Harmony", "Scanorama"]
single_methods: ["scDEF", "Unintegrated", "NMF", "scHPF"]
